# matrices in python

In [9]:
import numpy as np
import scipy as sp
import scipy.linalg as linalg

## ndarray vs matrix
ndarray is [recommended](http://docs.scipy.org/doc/scipy-0.14.0/reference/tutorial/linalg.html#numpy-matrix-vs-2d-numpy-ndarray)


### creating

In [16]:
A = sp.matrix([[1,2,3],[3,1,2],[4,5,7]])
a = np.array([[1,2,3],[3,1,2],[4,5,7]])
A, a

(matrix([[1, 2, 3],
         [3, 1, 2],
         [4, 5, 7]]), array([[1, 2, 3],
        [3, 1, 2],
        [4, 5, 7]]))

### transpose

In [13]:
A.T, a.T

(matrix([[1, 3, 4],
         [2, 1, 5],
         [3, 2, 7]]), array([[1, 3, 4],
        [2, 1, 5],
        [3, 2, 7]]))

### inverse

In [14]:
A.I, linalg.inv(a)

(matrix([[-0.75,  0.25,  0.25],
         [-3.25, -1.25,  1.75],
         [ 2.75,  0.75, -1.25]]), array([[-0.75,  0.25,  0.25],
        [-3.25, -1.25,  1.75],
        [ 2.75,  0.75, -1.25]]))

### matrix multiplication

In [24]:
B = np.matrix([2,2,3])
b = np.array([2,2,3])
A*B.T, a.dot(b)

(matrix([[15],
         [14],
         [39]]), array([15, 14, 39]))

### as vertical vector

In [40]:
B.T, b[:,np.newaxis]

(matrix([[2],
         [2],
         [3]]), array([[2],
        [2],
        [3]]))

### elementwise multiplication

In [27]:
np.multiply(A,B), a*b

(matrix([[ 2,  4,  9],
         [ 6,  2,  6],
         [ 8, 10, 21]]), array([[ 2,  4,  9],
        [ 6,  2,  6],
        [ 8, 10, 21]]))

In [33]:
np.multiply(A,B.T), a*b[:,np.newaxis]

(matrix([[ 2,  4,  6],
         [ 6,  2,  4],
         [12, 15, 21]]), array([[ 2,  4,  6],
        [ 6,  2,  4],
        [12, 15, 21]]))

## solving linear system
using inverse matrix is [not recommended](http://www.johndcook.com/blog/2010/01/19/dont-invert-that-matrix/)

### slow

In [54]:
a = np.random.randint(low=-10,high=10,size=(100,100))
b = np.random.randint(low=-10,high=10,size=(100))
%timeit linalg.inv(a).dot(b)

1000 loops, best of 3: 698 µs per loop


### fast

In [55]:
%timeit linalg.solve(a,b)

1000 loops, best of 3: 324 µs per loop


In [77]:
a = np.random.randint(low=0, high=10, size=(2,2))
b = np.random.randint(low=0, high=10, size=2)
a,b

(array([[8, 2],
        [0, 6]]), array([8, 8]))

In [78]:
linalg.solve(a,b)

array([ 0.66666667,  1.33333333])

## eigenvalues and eigenvector

If there exists a nonzero vector $x$ such that

$Ax = \lambda x$

then $\lambda$ is called $A$'s egenvalues and $x$ is $A$'s eigenvector.

** how to find $\lambda$ and $x$: **

$Ax = \lambda Ix$ add identidy matrix

$Ax - \lambda Ix = 0$ subtract one side

$(A - \lambda I)x = 0$ factorize

This have a solution when *det*$(A - \lambda I) = 0$. In case of a 2x2 matrix this gives the equation

$\begin{vmatrix}

\end{vmatrix}

In [79]:
help(linalg.eigh)

Help on function eigh in module scipy.linalg.decomp:

eigh(a, b=None, lower=True, eigvals_only=False, overwrite_a=False, overwrite_b=False, turbo=True, eigvals=None, type=1, check_finite=True)
    Solve an ordinary or generalized eigenvalue problem for a complex
    Hermitian or real symmetric matrix.
    
    Find eigenvalues w and optionally eigenvectors v of matrix `a`, where
    `b` is positive definite::
    
                      a v[:,i] = w[i] b v[:,i]
        v[i,:].conj() a v[:,i] = w[i]
        v[i,:].conj() b v[:,i] = 1
    
    Parameters
    ----------
    a : (M, M) array_like
        A complex Hermitian or real symmetric matrix whose eigenvalues and
        eigenvectors will be computed.
    b : (M, M) array_like, optional
        A complex Hermitian or real symmetric definite positive matrix in.
        If omitted, identity matrix is assumed.
    lower : bool, optional
        Whether the pertinent array data is taken from the lower or upper
        triangle of `a`. (D

In [80]:
values, vector = linalg.eigh(a)
values.shape, vector.shape

((2,), (2, 2))

In [81]:
print(values)

[ 6.  8.]


In [82]:
print(vector)

[[ 0. -1.]
 [-1. -0.]]
